<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date From_b5-b1-b2-Date_input</name>
   <tag></tag>
   <elementGuidId>892be86b-4035-43b4-8c59-edfe6c81a953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b1-b2-Date_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-b2-Date_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3786efb6-1b7c-4020-ae1a-be9c4c3ec9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>9ce1ab03-aad5-4fda-9b68-d53994bb16d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6d98d1b-1ae5-4372-80a4-5d5f9fde9f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f0c31862-3940-4cac-8f78-1e2fbbc1269c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-09</value>
      <webElementGuid>97311c87-382d-484d-bc6b-aa93e81806b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b1-b2-Date_input</value>
      <webElementGuid>a607b933-e92a-485a-b113-2a2bc062ed47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b1-b2-Date_input&quot;)</value>
      <webElementGuid>b747f7e6-f5d1-4b7a-ad80-42002ebc0e52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b1-b2-Date_input']</value>
      <webElementGuid>52e06c3e-ba15-4baa-a9da-5e43fe91c471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitionContainer']/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>8c652d20-d860-4c30-9e92-fe4e56b0ae1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>ab22ea7b-7864-4638-9c40-c62c75941169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b1-b2-Date_input']</value>
      <webElementGuid>4c9694e7-660b-45a4-bd92-87b8e0489a9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
