<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GOT IT</name>
   <tag></tag>
   <elementGuidId>36e834ea-2982-4dcc-976d-d44987fbe89a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.padding-top-s > button.btn.border-radius-rounded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>16339caf-2941-459d-a97b-810e4d10fff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn border-radius-rounded</value>
      <webElementGuid>fc8eb5fb-8582-4ec8-99f9-c77a90c55878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a875ff05-c560-404f-b44e-7062d8d5e050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GOT IT</value>
      <webElementGuid>d55cb4cb-8b4e-4f7e-8e59-f3346772561e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-b1-Bottom&quot;)/div[@class=&quot;padding-top-s&quot;]/button[@class=&quot;btn border-radius-rounded&quot;]</value>
      <webElementGuid>d08fb34e-d0cf-4139-8f91-3d92caf69067</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>5bb5c075-67ee-4533-9406-50203acfd519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b12-b1-Bottom']/div/button</value>
      <webElementGuid>6144a281-65c4-4482-b2cb-c82b49b49d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click App Feedback icon in the bottom right corner and submit your feedback.'])[1]/following::button[1]</value>
      <webElementGuid>98b9b1e8-ecf0-4bda-9df2-843d86cb1bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You find errors and bugs in the app? Report to us via App Feedback.'])[1]/following::button[1]</value>
      <webElementGuid>037405d8-e8ba-48e8-b4d8-26c2de6fe6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>9768a997-cc5e-46fd-a57e-ea64bb109f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'GOT IT' or . = 'GOT IT')]</value>
      <webElementGuid>10537354-0479-4377-98fd-d766759ea360</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
