<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>loginmodena</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5614a46c-85af-4349-89b4-fc35c46bd1a6</testSuiteGuid>
   <testCaseLink>
      <guid>88dadb66-296f-4caf-9a07-2b61c4c4138e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_loginmodena/tc_loginmodena</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>90094fe7-9ce0-46b3-ab7d-faa65a1eb0d6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TD_loginmodena/loginmodena</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>90094fe7-9ce0-46b3-ab7d-faa65a1eb0d6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>a546e2c6-bfa8-47a2-9dd6-e4828035117f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>90094fe7-9ce0-46b3-ab7d-faa65a1eb0d6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>2c264c37-9965-43c7-a3be-18c8493032b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>90094fe7-9ce0-46b3-ab7d-faa65a1eb0d6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_result</value>
         <variableId>4fd28114-4703-4e2e-87a2-679645d35b1a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
