<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date To_b5-b1-b3-Date_input</name>
   <tag></tag>
   <elementGuidId>073233cc-9127-4014-8ced-26e46d2c0dcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b1-b3-Date_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-b3-Date_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e767df0d-dc3d-44a3-ac05-703e2749cf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>c4979502-1eed-4ed5-b9d3-1c9a90d3df87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6d7eb65-7522-4f47-8a9b-012849a7e086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4579e32a-c72b-4487-9ed7-5e0e4589525f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-09</value>
      <webElementGuid>e57bfd30-a00e-4ce5-a713-3dd758c37b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b1-b3-Date_input</value>
      <webElementGuid>db70b093-cc7a-4f7f-9795-071069048ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b1-b3-Date_input&quot;)</value>
      <webElementGuid>863705d3-8b82-43ab-8816-ce92119699e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b1-b3-Date_input']</value>
      <webElementGuid>fa7a8f29-e790-47dc-8803-5af273c49f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitionContainer']/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>4673b729-e3f3-431f-94bb-19065c513b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>d36bffde-7365-414d-95ab-f60c24ee1a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b1-b3-Date_input']</value>
      <webElementGuid>dec0af2d-2d3c-4905-b877-ab91e2f95dcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
