<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ECO_b5-b3-l1-283_5-Checkbox1</name>
   <tag></tag>
   <elementGuidId>d56730f5-cbb8-4db2-9e31-1f575f0e35ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b3-l1-283_5-Checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b3-l1-283_5-Checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8503c3c6-0bee-4020-8162-9979b5f86201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox margin-right-s</value>
      <webElementGuid>3f5f12e6-8ceb-4b6d-9957-94b6219f142d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f4a66964-50e3-493d-ad99-8f262bc06875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b3-l1-283_5-Checkbox1</value>
      <webElementGuid>cea1d4b2-fc5d-4b72-8223-8f25de9f0a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b3-l1-283_5-Checkbox1&quot;)</value>
      <webElementGuid>254870cb-47e9-40c0-bc5e-d0582d04aa0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b3-l1-283_5-Checkbox1']</value>
      <webElementGuid>57484ba9-9e0f-4727-b8b9-382701fa25df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-l1-283_5-b2-Content']/span/input</value>
      <webElementGuid>ef2278f7-7df6-4194-9786-51f0db309885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/span/input</value>
      <webElementGuid>d5a0f7f8-e76c-4843-97dd-26648e145144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b5-b3-l1-283_5-Checkbox1']</value>
      <webElementGuid>85032799-c63a-4bde-9849-3032d900d64e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
