<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Service_b5-b3-l1-283_0-Checkbox1</name>
   <tag></tag>
   <elementGuidId>d538be18-935a-4f88-90f8-8ddb0eea5b82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-b3-l1-283_0-Checkbox1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b3-l1-283_0-Checkbox1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdf3cc5e-4fd6-44b5-8132-bbc10ea41df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox margin-right-s</value>
      <webElementGuid>de1546d0-f1fc-4139-99a4-955361d5bf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b52e2add-e2f1-4439-89d2-19954326611e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b3-l1-283_0-Checkbox1</value>
      <webElementGuid>a62710ca-10ed-4246-8fdf-9e07dade4f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b3-l1-283_0-Checkbox1&quot;)</value>
      <webElementGuid>d0472a0c-e5fa-4c2c-9c29-e2ee6c5ffee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b3-l1-283_0-Checkbox1']</value>
      <webElementGuid>f744e898-f08d-4254-b2c6-d4956a5e6296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-l1-283_0-b2-Content']/span/input</value>
      <webElementGuid>dd9fdc8a-23b4-4683-b71b-595b518b7c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>b5f95e0d-95d5-43ed-9ece-8cbc7d55f875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b5-b3-l1-283_0-Checkbox1']</value>
      <webElementGuid>5a2c4380-6584-4c07-b3f0-4ff31cd9bf64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
