<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ICE_b5-b3-l1-283_8-Checkbox1</name>
   <tag></tag>
   <elementGuidId>0a091a77-c355-4026-a5ee-bdb981143023</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b3-l1-283_8-Checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b3-l1-283_8-Checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3df59388-a88e-48d5-823a-399209012dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox margin-right-s</value>
      <webElementGuid>a19953f4-2456-4cbe-b776-6f5e4144c6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f479a216-3c94-4ed9-9b61-61b6384ab82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b3-l1-283_8-Checkbox1</value>
      <webElementGuid>a69228a6-fcbc-48ed-a5b5-90a1aa77565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b3-l1-283_8-Checkbox1&quot;)</value>
      <webElementGuid>4c83dfbb-29fe-42a3-b091-58973617b83e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b3-l1-283_8-Checkbox1']</value>
      <webElementGuid>377a68a4-8e7f-4301-a28a-11566ca0cb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-l1-283_8-b2-Content']/span/input</value>
      <webElementGuid>00a42e0f-e1f9-4e91-afcc-cb5503dad218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/span/input</value>
      <webElementGuid>9b8d15eb-ac2c-4ea4-8916-7317f09a1368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b5-b3-l1-283_8-Checkbox1']</value>
      <webElementGuid>e3b6e16f-119b-4541-a445-431410bbca2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
