<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date To_b5-b1-b3-Date_input</name>
   <tag></tag>
   <elementGuidId>042e442d-05e3-43f2-9a14-a1a621c65a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b1-b3-Date_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-b3-Date_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90c3bcc8-695d-4c77-b232-f5160ce05a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>7b87d5ae-dbd5-45ba-8935-3481f4679d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ee94204-6d13-490d-aea1-57cfeb329356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0b8b73d2-75a2-4c8b-87d0-86b7ea33b6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-09</value>
      <webElementGuid>0535fd03-eab6-4a39-88c6-4ac1b290c3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b1-b3-Date_input</value>
      <webElementGuid>29ca4667-e27d-486c-a942-bd13229ca9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transitionContainer&quot;)/div[@class=&quot;active-screen screen-container&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;layout layout-side fixed-header&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;main-content ThemeGrid_Container&quot;]/div[@class=&quot;content-middle&quot;]/div[@class=&quot;padding-base background-neutral-0 shadow-s border-radius-soft margin-bottom-base&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[1]/div[@class=&quot;ThemeGrid_Width6&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;columns columns2 gutter-base tablet-break-none phone-break-none&quot;]/div[@class=&quot;columns-item&quot;]/div[1]/div[@class=&quot;OSBlockWidget&quot;]/span[@class=&quot;input-text&quot;]/input[@id=&quot;b5-b1-b3-Date_input&quot;]</value>
      <webElementGuid>32d96fa4-4c11-4d98-8b43-a1e4ab487622</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b1-b3-Date_input']</value>
      <webElementGuid>ab0b453d-e80d-4556-b207-e52420c628f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitionContainer']/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>07fd04ff-f6a2-4f97-95cb-b13e7680bcd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>f0724ee6-8cde-4b2d-8c37-8daec3049254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b1-b3-Date_input']</value>
      <webElementGuid>c66a7a9a-29e7-451d-a08f-150b8a3c9235</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
