<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_tabGroupLocation</name>
   <tag></tag>
   <elementGuidId>43ad52dd-ce3f-41f4-86ce-7346b894f2a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipper Non Bulky'])[1]/following::div[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3635f79-35be-408a-8016-7ef3d0aa6c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-tabs-tab-btn</value>
      <webElementGuid>a48b2258-52fa-4c46-a8ec-4df148ca7ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>de0a2124-632b-4434-809f-febb727d98ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6353f7d8-582f-46f2-b497-98746fe14ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-tab</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>56a651fe-558e-42b1-8e3d-e01996cb298a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>23e76faf-3938-4332-be8f-defa6698201d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>efc075a8-7df9-465e-a28f-b0f6a4e1a644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12fb6421-47a8-4c92-81c7-277a194d9d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b9c1691a-f638-48b6-9536-15fb7ea7fcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>nz-tabs-0-tab-1</value>
      <webElementGuid>a40dc625-ab41-44eb-b31f-1cd993bb677e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Group Location</value>
      <webElementGuid>46a23e70-1f02-495f-a39b-c280037e19ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-layout[1]/nz-layout[@class=&quot;layout ant-layout ant-layout-has-sider&quot;]/nz-layout[@class=&quot;ant-layout&quot;]/nz-content[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;inner-content&quot;]/app-tabs[1]/nz-tabset[@class=&quot;ant-tabs ant-tabs-card ant-tabs-editable ant-tabs-editable-card ant-tabs-top ant-tabs-default&quot;]/nz-tabs-nav[@class=&quot;ant-tabs-nav ng-star-inserted&quot;]/div[@class=&quot;ant-tabs-nav-wrap&quot;]/div[@class=&quot;ant-tabs-nav-list&quot;]/div[@class=&quot;ant-tabs-tab ng-star-inserted&quot;]/div[@class=&quot;ant-tabs-tab-btn&quot;]</value>
      <webElementGuid>27882b2d-a355-45e6-b417-cdea474634fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipper Non Bulky'])[1]/following::div[12]</value>
      <webElementGuid>8f61c5a1-533f-4114-9a5c-adceb762bcb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipper Bulky'])[1]/following::div[13]</value>
      <webElementGuid>2ee9831f-300c-49e3-844d-a44beb1de95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Menu'])[1]/preceding::div[3]</value>
      <webElementGuid>9a009f87-92eb-4c08-8aca-9544d0b3912f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/preceding::div[5]</value>
      <webElementGuid>fc91a93e-b60d-4df8-9a8b-f7d2cece5ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>1a7af9cc-50c0-4aed-aac0-af29c1d28000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Group Location' or . = 'Group Location')]</value>
      <webElementGuid>df1c5706-f525-477f-abb9-74689f855044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
