<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_login</name>
   <tag></tag>
   <elementGuidId>c90fcfc1-8313-4fb3-a552-31dfd4f60c67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='login()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.f18.logn_lt.logn_btn.lh46</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d7cff6c-3336-4b8c-90b8-9517234d7126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6f2dbeb9-5143-4167-95bb-0585343b37f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f18 logn_lt logn_btn lh46</value>
      <webElementGuid>72cd96ca-d16f-4a34-a844-d31097476de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>login()</value>
      <webElementGuid>492fecee-1c27-4b22-a317-fbddc4fbbe9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>8f307f37-db2f-4e99-a75b-3ae9e663e763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginForm&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;logn_lb&quot;]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[13]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/a[@class=&quot;f18 logn_lt logn_btn lh46&quot;]</value>
      <webElementGuid>26b5d350-2e25-4d97-8160-057b279c8bda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='login()']</value>
      <webElementGuid>2fd95844-a0fa-4123-922b-43820f457895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/table/tbody/tr[13]/td/table/tbody/tr/td[2]/a</value>
      <webElementGuid>1e394aef-3919-4a3e-8838-5da5cb3330e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verification code(Non case sensitive)'])[1]/following::a[2]</value>
      <webElementGuid>4d24a35d-4c13-4d59-bdf9-fa20e9167c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::a[2]</value>
      <webElementGuid>20ed6b68-e3e5-44ad-9817-2cae2ce13d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT. Tri Adi Bersama'])[1]/preceding::a[1]</value>
      <webElementGuid>c4f004fa-7a6c-4d99-ab22-656cb3ebd86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>abd547c0-9e00-4292-9380-7231ce5b98d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>aac23595-68e9-4d77-8dc2-033ddc59d04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>443062c4-5a5d-4015-9f2a-87d266827c5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
