<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_captcha</name>
   <tag></tag>
   <elementGuidId>dcbd5fe4-960f-432b-b463-df506b68e0e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verifyCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verifyCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87637781-d5e5-4127-b700-37455b0d8032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55f3649a-91f6-4592-a10c-52b2d7889498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verifyCode</value>
      <webElementGuid>fd07aeac-97e9-4c78-9f6c-c65934aa5aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verifyCode</value>
      <webElementGuid>bfa65516-fc3d-4304-a54a-04c7630c83d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inp1 logn_iny</value>
      <webElementGuid>c27fc50e-1468-4c58-a68b-cfadef17e836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(event.keyCode == 13) login();</value>
      <webElementGuid>962cc31a-7292-487e-a6f1-656fe4e37d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifyCode&quot;)</value>
      <webElementGuid>171ba48a-86b7-4e2e-b216-7cb863dacbde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verifyCode']</value>
      <webElementGuid>5ff4f1b9-c0f5-4b89-be7e-cac66e3bf90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/table/tbody/tr[11]/td/table/tbody/tr/td/input</value>
      <webElementGuid>038f3e7b-7b55-4624-9727-0c784c2cc4a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td/table/tbody/tr/td/input</value>
      <webElementGuid>149c6c6c-1f41-4d6b-bc94-b7891c5541e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'verifyCode' and @id = 'verifyCode']</value>
      <webElementGuid>24ed4b7c-346d-4dbf-9c99-fa4b7083b195</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
