<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout_text-align-center</name>
   <tag></tag>
   <elementGuidId>3ad47320-d1c3-494f-bc53-5445f539793b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b8-Content']/div/div/a/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-align-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3971b195-9a71-40e7-a6d6-7e221087cbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-align-center</value>
      <webElementGuid>47c16c24-b49c-416b-847c-d0a00d5cc17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b8-Content&quot;)/div[@class=&quot;list list-group padding-top-s padding-left-base OSFillParent&quot;]/div[1]/a[1]/div[@class=&quot;menu-wrapper&quot;]/div[@class=&quot;text-align-center&quot;]</value>
      <webElementGuid>d754e755-b385-4d0c-aa6a-05a7a17e6d62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-Content']/div/div/a/div/div</value>
      <webElementGuid>29fda028-4396-444a-bee2-5357da72eede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[16]</value>
      <webElementGuid>193c5e8a-6d0b-46af-89ae-85d43e9da8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IW'])[1]/following::div[16]</value>
      <webElementGuid>c6fd8f46-4914-4e49-a999-1607692f1b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::div[1]</value>
      <webElementGuid>632ccb44-a4be-4616-b52b-803eb2bc7fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/preceding::div[3]</value>
      <webElementGuid>ad80c9bc-2499-456f-9660-d64a74ff7e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>990180be-48aa-46e2-8c75-5f764f4fb388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
