<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Summary</name>
   <tag></tag>
   <elementGuidId>a4b01206-4a0f-4f10-8a72-bc1f47fcf5e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-l1-122_0-b4-Title']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.active.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>17951eed-7c87-4f85-b1e4-8cdc798fdf88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>6dda684c-4a16-47e9-b6fe-65c299dd59fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active active</value>
      <webElementGuid>f1163f4f-eed6-4944-809e-ee766aaff751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/AwareWebDashboard/Summary</value>
      <webElementGuid>5efaf376-c4db-49c3-86b1-bc035ff22e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>8db9cb00-d280-4ce2-8cd0-6152c1ec7f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-122_0-b4-Title&quot;)/a[@class=&quot;active active&quot;]</value>
      <webElementGuid>1ccd57b5-50f4-47aa-ad5d-a44b9ddbe33d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-122_0-b4-Title']/a</value>
      <webElementGuid>951a255e-83ca-4397-98a6-d95c9fcc4824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bookings'])[1]/preceding::a[1]</value>
      <webElementGuid>5b3b1ed9-907f-4c4d-87dc-951d696eac02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/AwareWebDashboard/Summary')]</value>
      <webElementGuid>23028606-749c-493f-83c8-36d5d3949152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/a</value>
      <webElementGuid>c9e269ce-df52-4749-a5b5-21cc4392189f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/AwareWebDashboard/Summary' and (text() = 'Summary' or . = 'Summary')]</value>
      <webElementGuid>45b21be1-dff4-4a2a-a44a-9158497e988c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
