<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SDS_b5-b3-l1-283_4-Checkbox1</name>
   <tag></tag>
   <elementGuidId>2fcc72ca-3dc3-4cd2-a468-b101ac2082ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b3-l1-283_4-Checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b3-l1-283_4-Checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>539fd1cb-4245-4c95-b0cf-c8f6cbb678a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox margin-right-s</value>
      <webElementGuid>3d8a3d98-5efa-4c82-871f-d69693ed6848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cfde4e83-34b0-4229-91c0-24cf8f798009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b3-l1-283_4-Checkbox1</value>
      <webElementGuid>8332286b-a85c-4054-9282-1463d80ee84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b3-l1-283_4-Checkbox1&quot;)</value>
      <webElementGuid>95825338-da0e-4456-bc9e-70e2ab2dce51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b3-l1-283_4-Checkbox1']</value>
      <webElementGuid>76160a93-35d4-419a-b884-73ee21c56988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-l1-283_4-b2-Content']/span/input</value>
      <webElementGuid>afc71026-634f-424f-9cdf-7bbae425955c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span/input</value>
      <webElementGuid>ad6f87d2-6499-4825-8ad6-ccaf31410adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b5-b3-l1-283_4-Checkbox1']</value>
      <webElementGuid>31238261-2d47-40e4-b948-7c6151f48a44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
