<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date From_b5-b1-b2-Date_input</name>
   <tag></tag>
   <elementGuidId>f154c831-caed-4473-bc73-512dc2318d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b1-b2-Date_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-b2-Date_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b379e4ad-cb43-4f81-93f5-645747ea4228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>ba762454-709f-435f-aa11-2c175fc11e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5aaba0c-72fd-45b9-a1ca-4382d4d25710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>97278667-b68d-43e7-9e40-535681ce1928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-08</value>
      <webElementGuid>231ddf67-dd8c-48fa-a1ab-0ba899494049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b1-b2-Date_input</value>
      <webElementGuid>1726b12c-7c96-4b1e-8b81-71cce1e6634e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transitionContainer&quot;)/div[@class=&quot;active-screen screen-container&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;layout layout-side fixed-header&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;main-content ThemeGrid_Container&quot;]/div[@class=&quot;content-middle&quot;]/div[@class=&quot;padding-base background-neutral-0 shadow-s border-radius-soft&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;padding-bottom-s&quot;]/div[@class=&quot;ThemeGrid_Width6&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;columns columns2 gutter-base tablet-break-none phone-break-none&quot;]/div[@class=&quot;columns-item&quot;]/div[1]/div[@class=&quot;OSBlockWidget&quot;]/span[@class=&quot;input-text&quot;]/input[@id=&quot;b5-b1-b2-Date_input&quot;]</value>
      <webElementGuid>b151afd7-b9b6-4cae-8ad9-d7e4c694fb8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b1-b2-Date_input']</value>
      <webElementGuid>2ab28477-1d68-44ad-9fd8-27e9ebd9c22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitionContainer']/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>0a1f81da-791d-4be5-9c30-a7c788994c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>25ad8724-66f8-4b62-bcb8-fac4e93ddf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b1-b2-Date_input']</value>
      <webElementGuid>a6980d3a-a6f2-4400-b7fd-d3b2de316c35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
