<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CSD_b5-b3-l1-283_9-Checkbox1</name>
   <tag></tag>
   <elementGuidId>a73447ac-d86b-4623-aa87-94393cae2df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b3-l1-283_9-Checkbox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b3-l1-283_9-Checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdb561d1-9bfb-4ac8-b222-35d2cd7f7853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox margin-right-s</value>
      <webElementGuid>9a30e7ad-ae6f-46a8-baba-4c3e8ac8222a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e6b9d267-356f-4538-b653-41799d1cf573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b3-l1-283_9-Checkbox1</value>
      <webElementGuid>bc3048d3-e966-4c0d-a455-75ee2aabc529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b3-l1-283_9-Checkbox1&quot;)</value>
      <webElementGuid>05d1d172-45a2-4f57-bb58-89727fec006e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b3-l1-283_9-Checkbox1']</value>
      <webElementGuid>6cb38cce-03ef-4d63-a384-5bfd464be158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-l1-283_9-b2-Content']/span/input</value>
      <webElementGuid>b7a61569-2c14-4ee3-814f-a3d307d4f664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/span/input</value>
      <webElementGuid>005062eb-6791-433c-a61c-870b21174b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b5-b3-l1-283_9-Checkbox1']</value>
      <webElementGuid>0f0c6c67-183b-42e8-b3b1-0f164062d012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
