<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date From_b5-b1-b2-Date_input</name>
   <tag></tag>
   <elementGuidId>c424930b-d716-459d-a031-c5a618edefa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b1-b2-Date_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-b2-Date_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8d7d770-4ada-42d7-93fb-beabfce66190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>c01ab0e3-0726-4b5a-b6ef-80d334a72647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38c883da-6056-4fa9-a78b-c8f97e0671ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>16f44bc4-26f5-4195-8659-0cd8137c60b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-09</value>
      <webElementGuid>dbaed7cb-288b-4254-9bd1-1d740ccd6f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b1-b2-Date_input</value>
      <webElementGuid>171268ae-802f-4de2-b491-c517dd858565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transitionContainer&quot;)/div[@class=&quot;active-screen screen-container&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;layout layout-side fixed-header&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;main-content ThemeGrid_Container&quot;]/div[@class=&quot;content-middle&quot;]/div[@class=&quot;padding-base background-neutral-0 shadow-s border-radius-soft margin-bottom-base&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[1]/div[@class=&quot;ThemeGrid_Width6&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;columns columns2 gutter-base tablet-break-none phone-break-none&quot;]/div[@class=&quot;columns-item&quot;]/div[1]/div[@class=&quot;OSBlockWidget&quot;]/span[@class=&quot;input-text&quot;]/input[@id=&quot;b5-b1-b2-Date_input&quot;]</value>
      <webElementGuid>7f9e21e7-eb74-4e10-ad15-ea2ca5df1aca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b1-b2-Date_input']</value>
      <webElementGuid>e526b6fe-35b4-440b-bcaa-d35b8a47bf99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitionContainer']/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>2c908644-bd9a-4e9c-a359-85f97b8a32a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>6a9b2140-6af4-41d7-9778-091f3fce7e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b1-b2-Date_input']</value>
      <webElementGuid>ef75e6cc-c2c0-4328-a2f0-884b00daaa43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
