<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date From_b5-b1-b2-Date_input</name>
   <tag></tag>
   <elementGuidId>da00f550-a66b-4dd3-8517-0159c9e29f4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b1-b2-Date_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-b2-Date_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6019a5f-e9e8-4efe-8666-a97b88f377e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>9ae49a31-4f13-4e65-a8fd-0c1a4cb0e6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76a84f45-7202-4128-be9a-09dedf0439e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1aff92fd-9123-4d06-85f2-7683d6491692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-08</value>
      <webElementGuid>9d42f155-88a8-4de3-90c4-b657390c824a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b1-b2-Date_input</value>
      <webElementGuid>3a504d75-bcc4-472f-a1d5-e43034861286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b1-b2-Date_input&quot;)</value>
      <webElementGuid>280b3ab4-d324-4ad5-b145-37d365b90651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b1-b2-Date_input']</value>
      <webElementGuid>2861ef16-a2f0-4778-a277-c6027824d966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitionContainer']/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>fdc4e4be-12dd-436d-a285-a5044c4fb4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>1c2db316-7619-4c3a-97eb-233127a5b2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b1-b2-Date_input']</value>
      <webElementGuid>5b26f7c9-b400-497f-9912-4c0e95a103ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
