<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date To_b5-b1-b3-Date_input</name>
   <tag></tag>
   <elementGuidId>bc2bc822-59d3-4384-9280-ba33c9728401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b1-b3-Date_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-b3-Date_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25c92cec-e47a-490d-b3d0-51bb53b4fb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e397f5bc-5435-4e07-a16f-c64bbd91b964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a585b076-8915-4f2c-ba29-e39227dbbf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6b391de4-0278-4df1-ac14-499a3a82bc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-09</value>
      <webElementGuid>8957cc66-9364-44bb-9ac4-44f4baa593f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b1-b3-Date_input</value>
      <webElementGuid>7586d8dd-8422-415a-b3ec-bbb464c3e38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transitionContainer&quot;)/div[@class=&quot;active-screen screen-container&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;layout layout-side fixed-header&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;main-content ThemeGrid_Container&quot;]/div[@class=&quot;content-middle&quot;]/div[@class=&quot;padding-base background-neutral-0 shadow-s border-radius-soft margin-bottom-base&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[1]/div[@class=&quot;ThemeGrid_Width6&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;columns columns2 gutter-base tablet-break-none phone-break-none&quot;]/div[@class=&quot;columns-item&quot;]/div[1]/div[@class=&quot;OSBlockWidget&quot;]/span[@class=&quot;input-text&quot;]/input[@id=&quot;b5-b1-b3-Date_input&quot;]</value>
      <webElementGuid>53621053-fba5-4f2b-aaf1-5734d75032c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b1-b3-Date_input']</value>
      <webElementGuid>b72e5493-32f2-4581-a275-690c0ace19b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitionContainer']/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>958bd01b-5389-4fbe-947b-0463319eb50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>18d7d4fe-3ba2-4ef6-81cf-7bfe7b368f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b1-b3-Date_input']</value>
      <webElementGuid>2f7d15ba-53eb-4f55-a169-3a3f610cf02b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
