<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date From_b5-b1-b2-Date_input</name>
   <tag></tag>
   <elementGuidId>c4cb6fe5-6281-4c18-9ef3-1a61e38e4184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b1-b2-Date_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b1-b2-Date_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9a5456f-c51e-4998-b8e8-9381eef4d0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>a0b0a19a-8ba1-493e-8548-c2d8796e4631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e63612f-51ee-46b7-b8e6-dfa0bf841d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>48edcbf4-3294-47db-b309-79af3f3c5fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-11-09</value>
      <webElementGuid>abea231d-9538-497b-9c11-5eb4e4998a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b1-b2-Date_input</value>
      <webElementGuid>57c51887-249d-4332-96b6-4f4c83e109a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transitionContainer&quot;)/div[@class=&quot;active-screen screen-container&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;layout layout-side fixed-header&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;main-content ThemeGrid_Container&quot;]/div[@class=&quot;content-middle&quot;]/div[@class=&quot;padding-base background-neutral-0 shadow-s border-radius-soft margin-bottom-base&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[1]/div[@class=&quot;ThemeGrid_Width6&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;OSBlockWidget&quot;]/div[@class=&quot;columns columns2 gutter-base tablet-break-none phone-break-none&quot;]/div[@class=&quot;columns-item&quot;]/div[1]/div[@class=&quot;OSBlockWidget&quot;]/span[@class=&quot;input-text&quot;]/input[@id=&quot;b5-b1-b2-Date_input&quot;]</value>
      <webElementGuid>6fe16581-b2f8-49df-b358-5018aa18c225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b1-b2-Date_input']</value>
      <webElementGuid>48ce9ec3-5c51-4ffd-a159-589d732aa3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='transitionContainer']/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>4f7ffce6-71d3-4730-a563-d43395bde270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/span/input</value>
      <webElementGuid>06b04cdc-cba6-484d-96ea-05e3efad1850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b1-b2-Date_input']</value>
      <webElementGuid>a2fd80d5-e38e-45b2-bc88-31371f9a3efc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
