<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout_text-align-center</name>
   <tag></tag>
   <elementGuidId>175d2b8f-635d-4775-9b7f-fc83b5fdd94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b8-Content']/div/div/a/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-align-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e259373-f94b-4023-a591-9ee9fa9a8780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-align-center</value>
      <webElementGuid>d2938113-8fcc-4867-89e8-5d16945a966d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b8-Content&quot;)/div[@class=&quot;list list-group padding-top-s padding-left-base OSFillParent&quot;]/div[1]/a[1]/div[@class=&quot;menu-wrapper&quot;]/div[@class=&quot;text-align-center&quot;]</value>
      <webElementGuid>88809e47-0a84-4bc5-b9d9-60db23a3ce95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b8-Content']/div/div/a/div/div</value>
      <webElementGuid>c05f0018-c578-42c9-aca6-1be1687aba58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::div[16]</value>
      <webElementGuid>be91f90a-46b6-4c9e-8835-246249e25a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IW'])[1]/following::div[16]</value>
      <webElementGuid>112fec06-49b0-4c5b-b3ae-2b3782289661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::div[1]</value>
      <webElementGuid>6c5f3209-0e39-456e-93e0-0913534078fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/preceding::div[3]</value>
      <webElementGuid>b2dc81b7-56be-4687-87f1-a44081a5cc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>c808eff7-68f9-4c47-b89e-0fedeaf86e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
