<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Aware WebLoginOr Login with</name>
   <tag></tag>
   <elementGuidId>b717b50e-3e14-4847-9e58-0d3c7fc8f7b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='LoginForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LoginForm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>53f2d8ac-1e00-4834-9582-e140558f4802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-form</value>
      <webElementGuid>449e35cc-c848-41b7-9422-464da4d7071e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LoginForm</value>
      <webElementGuid>0b22a142-9878-417f-8669-7ba05dd297d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aware WebLoginOr Login with:</value>
      <webElementGuid>5a1baa23-004a-45ce-b24e-a23f6cf4083b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginForm&quot;)</value>
      <webElementGuid>9ba71f04-8fca-48fd-a93b-a3006d1cee8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='LoginForm']</value>
      <webElementGuid>39371b4f-a5c9-4b46-b441-7861461b05f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-Content']/div/form</value>
      <webElementGuid>459f266c-3694-4daa-a1a4-6c8b75f187d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>972734ab-1141-4936-ac47-7fcaef03519c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'LoginForm' and (text() = 'Aware WebLoginOr Login with:' or . = 'Aware WebLoginOr Login with:')]</value>
      <webElementGuid>fe82b87b-515b-457c-bf94-aad07bd6dd01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
