<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>134a80f8-af6f-4b6d-82e8-951c5676b64b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-Active']/div/div/div[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ThemeGrid_Width6.ThemeGrid_MarginGutter > a > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>391f6aae-24e3-41a5-8994-b3efa0d18415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/AwareWeb/img/AwareWeb.office365.svg?quiYPox+baTVtL40lBqJEQ</value>
      <webElementGuid>41493b3f-18f2-40a0-97f4-8443e11104ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Active&quot;)/div[@class=&quot;margin-top-m&quot;]/div[@class=&quot;text-align-right ThemeGrid_Width8 ThemeGrid_MarginGutter&quot;]/div[@class=&quot;ThemeGrid_Width6 ThemeGrid_MarginGutter&quot;]/a[1]/img[1]</value>
      <webElementGuid>6f7fd847-652a-4cbc-ad63-a7221cb00eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-Active']/div/div/div[2]/a/img</value>
      <webElementGuid>ae8de2d1-e475-4608-9385-879bb68bdff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>2ddf5d7e-81b1-4be4-91db-a76924f62fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/AwareWeb/img/AwareWeb.office365.svg?quiYPox+baTVtL40lBqJEQ']</value>
      <webElementGuid>f8a278da-83fc-4bc0-9ec1-a54df92a2b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
